import Head from "next/head";
import Navbar from "@/components/Navbar";
import { Aboutinfo, Testimonial } from "@/components/About";
import { ServicesInfo } from "@/components/Services";
import { PizzaMeals, Products } from "@/components/Menu";
import Footer from "@/components/Footer";
import Main from "@/components/Home";
import bg_1 from "../public/images/bg_1.jpg";
import bg_3 from "../public/images/bg_3.jpg";
import bg_4 from "../public/images/bg_4.jpg";
import gallery_1 from "../public/images/gallery-1.jpg";
import gallery_2 from "../public/images/gallery-2.jpg";
import gallery_3 from "../public/images/gallery-3.jpg";
import gallery_4 from "../public/images/gallery-4.jpg";
import favicon from "../public/favicon.ico";

export default function Home() {
	return (
		<>
			<Head>
				<title>Pizza</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={favicon.src} />
			</Head>
			<Navbar />
			<Main />
			<div
				style={{ backgroundImage: `url(${bg_4.src})` }}
				className=" bg-cover bg-no-repeat bg-center bg-fixed text-white"
			>
				<Aboutinfo />
			</div>
			<ServicesInfo />
			<div
				style={{ backgroundImage: `url(${bg_4.src})` }}
				className="text-white bg-no-repeat bg-fixed"
			>
				<PizzaMeals heading="HOT PIZZA MEALS" />
			</div>
			<div className="md:flex">
				<div
					style={{ backgroundImage: `url(${gallery_1.src})` }}
					className="relative w-full bg-cover bg-center bg-no-repeat h-[300px]"
				></div>
				<div
					style={{ backgroundImage: `url(${gallery_2.src})` }}
					className="relative w-full bg-cover bg-center bg-no-repeat h-[300px]"
				></div>
				<div
					style={{ backgroundImage: `url(${gallery_3.src})` }}
					className="relative w-full bg-cover bg-center bg-no-repeat h-[300px]"
				></div>
				<div
					style={{ backgroundImage: `url(${gallery_4.src})` }}
					className="relative w-full bg-cover bg-center bg-no-repeat h-[300px]"
				></div>
			</div>
			<Testimonial />
			<div
				style={{ backgroundImage: `url(${bg_4.src})` }}
				className="text-white bg-no-repeat bg-fixed"
			>
				<Products />
			</div>
			<Footer />
		</>
	);
}
